### PR TITLE
Fix/532/input restriction  manual support list

### LINKED ISSUE #532: Adding minus sign is blanking the field for Angle/arm length in section
### Describe the current behavior

[SIG-1.03.00-INT.026 : Saisie du signe "-" impossible sans effacer la valeur du champ "Angle" ou "L. bras"](https://gopro-collaboratif.rte-france.com/pages/viewpage.action?pageId=551160839)

### Describe the expected behavior

_No response_

### Describe the steps

_No response_

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by pikr-fra-RTE**
PR for #532

### CODE REVIEW

**Review by PascalSeniziRTE — APPROVED** [review]

**Review by PascalSeniziRTE — APPROVED** [review]

File: src/app/ui/pages/study/tabs/sections/newSectionModal/manualSection/supportsTable/supportsTable.component.ts [hunk 1]
```diff
@@ -185,4 +189,12 @@ export class SupportsTableComponent implements OnInit {
   isNumber(value: unknown) {
     return isNumber(value);
   }
+
+  truncateDecimals(event: Event): void {
+    const input = event.target as HTMLInputElement;
+    const sepIndex = input.value.indexOf('.');
+    if (sepIndex !== -1 && input.value.substring(sepIndex + 1).length > 2) {
+      input.value = input.value.substring(0, sepIndex + 3);
```
[the remark this answers is not in the document]
Comment (pikr-fra-RTE) [reply src/app/ui/pages/study/tabs/sections/newSectionModal/manualSection/supportsTable/supportsTable.component.ts:197]: Nope. Cause the event is "input". We listen to the actual value of the input number and as a value, "1,2" = "1.2" :)
Nice try copilot but you had to check the actual event which run this function

File: src/app/ui/pages/studio/studio-page.component.html [hunk 2]
```diff
@@ -16,36 +16,40 @@
...
-          <span class="quick-measures__value">123</span>
-        </p>
-
-        <p>
-          <span class="quick-measures__title" i18n>Work load %</span>
-          <span class="quick-measures__value">123</span>
-        </p>
+    <div>
+      <div class="quick-measures">
+        <dl class="contents">
```
Comment (frenix0076) [inline src/app/ui/pages/studio/studio-page.component.html]: To better comply with BEM conventions, I suggest replacing **contents** with **quick-measures__list**.

File: src/app/ui/pages/studio/studio-page.component.html [hunk 3]
```diff
@@ -16,36 +16,40 @@
...
-        <p>
-          <span class="quick-measures__title" i18n>Vertical (m)</span>
-          <span class="quick-measures__value"></span>
-        </p>
-
-        <p>
-          <span class="quick-measures__title" i18n>Horizontal (m)</span>
-          <span class="quick-measures__value"></span>
-        </p>
+        <dl class="contents">
```
Comment (frenix0076) [inline src/app/ui/pages/studio/studio-page.component.html]: To better comply with BEM conventions, I suggest replacing contents with quick-measures__list.

File: src/app/ui/pages/study/tabs/sections/newSectionModal/newSectionModal.component.ts [hunk 4]
```diff
@@ -47,6 +48,17 @@ const areAllRequiredFieldsFilled = (section: Section) => {
   );
 };
 
+const hasSupportsBoundsErrors = (section: Section): boolean => {
```
Comment (frenix0076) [inline src/app/ui/pages/study/tabs/sections/newSectionModal/newSectionModal.component.ts]: We should move the constants out of the component and place them in a dedicated ***.constants.ts** file.

File: src/app/ui/shared/components/atoms/button/button.component.ts [hunk 5]
```diff
@@ -19,7 +19,19 @@ import { IconComponent } from '../icon/icon.component';
 export class ButtonComponent implements OnInit, OnDestroy {
   private clickListener?: (e: Event) => void;
 
-  constructor(private readonly elementRef: ElementRef<HTMLButtonElement | HTMLLinkElement>) {}
+  constructor(private readonly elementRef: ElementRef<HTMLButtonElement | HTMLLinkElement>) {
```
Comment (frenix0076) [inline src/app/ui/shared/components/atoms/button/button.component.ts]: not constructor use computed for classesList

**Review by frenix0076 — APPROVED** [review]
