### PR TITLE
Feat/447/create and visualize obstacle fix

### LINKED ISSUE #447: Create and visualize an obstacle
[US.OBS.STU.1 - Créer et visualiser un obstacle](https://gopro-collaboratif.rte-france.com/pages/viewpage.action?pageId=539206309&src=contextnavpagetreemode)

**As the author of a study,**  
**I want** to create, visualize, and save one or several obstacles on one or multiple spans of a block section in my study,  
**so that** I can highlight the obstacles located along the block section within my study’s Studio.

Image

### PR DESCRIPTION
**Pull request by PascalSeniziRTE**
**Please check if the PR fulfills these requirements**

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

[#447](https://github.com/phlowers/phlowers-stellar-app/issues/447) 

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *breaking change* or *deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

File: src/app/ui/shared/components/studio/free-positioning/free-positioning.component.ts [hunk 1]
```diff
@@ -464,6 +486,15 @@ export class FreePositioningComponent implements OnDestroy {
...
+    this.plotService.isFreePositioningMode.set(false);
     this.destroyAllPlots();
   }
+
+  @HostListener('document:keydown.escape', ['$event'])
+  onEscape(event: KeyboardEvent): void {
+    if (!this.plotService.isFreePositioningMode()) return;
+    event.preventDefault();
+    this.plotService.isFreePositioningMode.set(false);
+  }
```
Comment (pikr-fra-RTE) [inline src/app/ui/shared/components/studio/free-positioning/free-positioning.component.ts]: Kill free positioning on escape key was a request?

Comment (PascalSeniziRTE) [reply src/app/ui/shared/components/studio/free-positioning/free-positioning.component.ts]: No, you are right

**Review by pikr-fra-RTE — APPROVED** [review]
