### PR TITLE
#435 Fix update when updating pyodide

### LINKED ISSUE #435: 🔄 Fix app update when updating pyodide
### Describe the current behavior

When updating pyodide, we cant update because the app does not refresh pyodide files

### Describe the expected behavior

_No response_

### Describe the steps

_No response_

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by mjozan-rte**
#435 
**Please check if the PR fulfills these requirements**

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *breaking change* or *deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

File: src/app/core/services/worker_update/service-worker.ts [hunk 1]
```diff
@@ -145,44 +146,6 @@ export async function handleFetch(event: FetchEvent) {
   handleFetch
 );
 
-(self as unknown as ServiceWorkerGlobalScope).addEventListener(
```
Comment (mjozan-rte) [inline src/app/core/services/worker_update/service-worker.ts:148]: this function is duplicated

**Review by PascalSeniziRTE — APPROVED** [review]
