### PR TITLE
fix modal transition between init and main for toolbar-dialog

### LINKED ISSUE #505: fix transition between field measuring init and main modal
### Describe the current behavior

When validating the field measuring tool modal init, the transition to main modal doesn't happen and modal closed.
The bug wasn't observed in dev stage but is present after feature merge (rebase error or cache induced sense of completion)

### Describe the expected behavior

The field measuring init validation should lead to main modal after close instead of just closing and stopping there.

### Describe the steps

- Open a study in the studio.
- launch the field measuring modal.
- Create a new measuring or select an existing one.
- validate.
- aaaand... it's gone!

Image

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by pikr-fra-RTE**
Fix the bug encountered for transition between init and main content modal with toolbar-dialog.
timeout method was too weak to rely on for transition. Now using native primeNG visibleChange event to flag the current state for init / main

### CODE REVIEW

File: src/app/ui/pages/studio/toolbar-dialog/toolbar-dialog.component.ts [hunk 1]
```diff
@@ -12,8 +12,17 @@ export class ToolbarDialogComponent {
...
+  onVisibleChange(visible: boolean): void {
+    if (!visible && this.toolbarDialogService.isTransitioning()) {
+      return;
+    }
+    this.toolbarDialogService.isOpen.set(visible);
+  }
+
   onDialogHide(): void {
-    if (!this.toolbarDialogService.isTransitioning()) {
+    if (this.toolbarDialogService.isTransitioning()) {
```
Comment (frenix0076) [inline src/app/ui/pages/studio/toolbar-dialog/toolbar-dialog.component.ts]: There is only one statement inside the if/else. Prefer the ternary operator for single statements and use if/else for multiple statements.

**Review by mjozan-rte — APPROVED** [review]

**Review by frenix0076 — APPROVED** [review]

**Review by PascalSeniziRTE — APPROVED** [review]
